[package]
name = "squatternaut"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
csv = "1"
db-dump = "0.6"
semver = "1"
serde = "1"
serde_derive = "1"
termcolor = "1"
